# Generated by Django 3.2.10 on 2022-02-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, null=True)),
                ('password', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='resitration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=40, null=True)),
                ('address_1', models.CharField(max_length=80, null=True)),
            ],
        ),
    ]
