# Generated by Django 3.2.10 on 2022-02-26 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resitration',
            table='resitration',
        ),
    ]
