# Generated by Django 3.2.10 on 2022-02-27 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_resitration_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resitration',
            name='address_1',
        ),
    ]
