# Generated by Django 3.2.10 on 2022-02-27 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_resitration_address_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resitration',
            old_name='password',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='resitration',
            name='address_1',
        ),
        migrations.RemoveField(
            model_name='resitration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='resitration',
            name='username',
        ),
        migrations.AlterModelTable(
            name='resitration',
            table=None,
        ),
    ]
