# Generated by Django 3.2.10 on 2022-07-07 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20220707_1017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
