# Generated by Django 3.2.10 on 2022-07-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_image_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, null=True)),
                ('Controller', models.ImageField(upload_to='images')),
                ('description', models.CharField(max_length=350, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmbeddedLinux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, null=True)),
                ('EmbeddedLinux', models.ImageField(upload_to='images')),
                ('description', models.CharField(max_length=350, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PcbDesigning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, null=True)),
                ('PcbDesigning', models.ImageField(upload_to='images')),
                ('description', models.CharField(max_length=350, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, null=True)),
                ('WebApp', models.ImageField(upload_to='images')),
                ('description', models.CharField(max_length=350, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='image',
        ),
    ]
