# Generated by Django 3.2.10 on 2022-08-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20220724_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controller',
            name='Controller',
        ),
        migrations.RemoveField(
            model_name='embeddedlinux',
            name='EmbeddedLinux',
        ),
        migrations.RemoveField(
            model_name='pcbdesigning',
            name='PcbDesigning',
        ),
        migrations.RemoveField(
            model_name='webapp',
            name='WebApp',
        ),
        migrations.AddField(
            model_name='controller',
            name='blurController',
            field=models.ImageField(default='blur-image.jpeg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='controller',
            name='originalController',
            field=models.ImageField(null=True, upload_to='original_image'),
        ),
        migrations.AddField(
            model_name='embeddedlinux',
            name='blurEmbeddedLinux',
            field=models.ImageField(default='blur-image.jpeg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='embeddedlinux',
            name='originalEmbeddedLinux',
            field=models.ImageField(null=True, upload_to='original_image'),
        ),
        migrations.AddField(
            model_name='pcbdesigning',
            name='blurPcbDesigning',
            field=models.ImageField(default='blur-image.jpeg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='pcbdesigning',
            name='originalPcbDesigning',
            field=models.ImageField(null=True, upload_to='original_image'),
        ),
        migrations.AddField(
            model_name='webapp',
            name='blurWebApp',
            field=models.ImageField(default='blur-image.jpeg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='webapp',
            name='originalWebApp',
            field=models.ImageField(null=True, upload_to='original_image'),
        ),
    ]
