# Generated by Django 3.2.10 on 2022-08-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20220820_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddedlinux',
            name='originalEmbeddedLinux',
            field=models.ImageField(null=True, upload_to='original_image_01'),
        ),
    ]
