# Generated by Django 3.2.10 on 2022-08-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_embeddedlinux_originalembeddedlinux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcbdesigning',
            name='originalPcbDesigning',
            field=models.ImageField(null=True, upload_to='original_image_02'),
        ),
        migrations.AlterField(
            model_name='webapp',
            name='originalWebApp',
            field=models.ImageField(null=True, upload_to='original_image_03'),
        ),
    ]
