# Generated by Django 3.2.12 on 2022-09-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20220820_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='insideContains',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
