# Generated by Django 3.2.12 on 2022-09-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_controller_insidecontains'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='TestingByDirectHTml',
            field=models.FileField(null=True, upload_to='posrtHtmls'),
        ),
    ]
