# Generated by Django 3.2.12 on 2022-09-24 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_controller_testingbydirecthtml'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controller',
            name='TestingByDirectHTml',
        ),
    ]
