# Generated by Django 3.2.12 on 2022-09-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_controller_insidecontains'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='image2',
            field=models.ImageField(null=True, upload_to='original_image'),
        ),
    ]
