# Generated by Django 3.2.12 on 2022-09-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_controller_image2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controller',
            old_name='image2',
            new_name='image01',
        ),
        migrations.AddField(
            model_name='controller',
            name='image02',
            field=models.ImageField(null=True, upload_to='original_image'),
        ),
        migrations.AddField(
            model_name='controller',
            name='image03',
            field=models.ImageField(null=True, upload_to='original_image'),
        ),
        migrations.AddField(
            model_name='controller',
            name='image04',
            field=models.ImageField(null=True, upload_to='original_image'),
        ),
    ]
