# Generated by Django 3.2.12 on 2022-09-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_auto_20220926_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='image01',
            field=models.ImageField(null=True, upload_to='original_image01'),
        ),
        migrations.AlterField(
            model_name='controller',
            name='image02',
            field=models.ImageField(null=True, upload_to='original_image02'),
        ),
        migrations.AlterField(
            model_name='controller',
            name='image03',
            field=models.ImageField(null=True, upload_to='original_image03'),
        ),
        migrations.AlterField(
            model_name='controller',
            name='image04',
            field=models.ImageField(null=True, upload_to='original_image04'),
        ),
    ]
