# Generated by Django 3.2.12 on 2022-09-26 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_alter_controller_image01'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controller',
            name='image01',
        ),
        migrations.RemoveField(
            model_name='controller',
            name='image02',
        ),
        migrations.RemoveField(
            model_name='controller',
            name='image03',
        ),
        migrations.RemoveField(
            model_name='controller',
            name='image04',
        ),
    ]
