# Generated by Django 3.2.10 on 2022-09-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_auto_20220926_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controller',
            name='insideContains',
        ),
        migrations.AddField(
            model_name='controller',
            name='multiController1',
            field=models.ImageField(null=True, upload_to='original_image'),
        ),
        migrations.AddField(
            model_name='controller',
            name='multiController2',
            field=models.ImageField(null=True, upload_to='original_image'),
        ),
        migrations.AddField(
            model_name='controller',
            name='multiController3',
            field=models.ImageField(null=True, upload_to='original_image'),
        ),
        migrations.AddField(
            model_name='controller',
            name='multiController4',
            field=models.ImageField(null=True, upload_to='original_image'),
        ),
    ]
