# Generated by Django 3.2.10 on 2022-09-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_auto_20220930_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='embeddedlinux',
            name='multiImgEmb1',
            field=models.ImageField(null=True, upload_to='original_image'),
        ),
        migrations.AddField(
            model_name='embeddedlinux',
            name='multiImgEmb2',
            field=models.ImageField(null=True, upload_to='original_image'),
        ),
        migrations.AddField(
            model_name='embeddedlinux',
            name='multiImgEmb3',
            field=models.ImageField(null=True, upload_to='original_image'),
        ),
        migrations.AddField(
            model_name='embeddedlinux',
            name='multiImgEmb4',
            field=models.ImageField(null=True, upload_to='original_image'),
        ),
    ]
