# Generated by Django 3.2.10 on 2022-10-02 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_auto_20220930_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controller',
            name='multiController1',
        ),
        migrations.RemoveField(
            model_name='controller',
            name='multiController2',
        ),
        migrations.RemoveField(
            model_name='controller',
            name='multiController3',
        ),
        migrations.RemoveField(
            model_name='controller',
            name='multiController4',
        ),
        migrations.RemoveField(
            model_name='embeddedlinux',
            name='multiImgEmb1',
        ),
        migrations.RemoveField(
            model_name='embeddedlinux',
            name='multiImgEmb2',
        ),
        migrations.RemoveField(
            model_name='embeddedlinux',
            name='multiImgEmb3',
        ),
        migrations.RemoveField(
            model_name='embeddedlinux',
            name='multiImgEmb4',
        ),
    ]
