# Generated by Django 4.1.3 on 2022-11-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_auto_20221003_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='html_code',
            field=models.TextField(blank=True),
        ),
    ]
