# Generated by Django 4.1.3 on 2022-11-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_controller_html_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embeddedlinux',
            name='multiImgEmb1',
        ),
        migrations.RemoveField(
            model_name='embeddedlinux',
            name='multiImgEmb2',
        ),
        migrations.RemoveField(
            model_name='embeddedlinux',
            name='multiImgEmb3',
        ),
        migrations.RemoveField(
            model_name='embeddedlinux',
            name='multiImgEmb4',
        ),
        migrations.AddField(
            model_name='embeddedlinux',
            name='html_code',
            field=models.TextField(blank=True),
        ),
    ]
