# Generated by Django 4.1.3 on 2022-11-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_remove_embeddedlinux_multiimgemb1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcbdesigning',
            name='html_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='webapp',
            name='html_code',
            field=models.TextField(blank=True),
        ),
    ]
