# Generated by Django 4.1.3 on 2022-11-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_pcbdesigning_html_code_webapp_html_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='image2',
            field=models.ImageField(null=True, upload_to='original_image'),
        ),
        migrations.AddField(
            model_name='controller',
            name='image3',
            field=models.ImageField(null=True, upload_to='original_image'),
        ),
        migrations.AddField(
            model_name='controller',
            name='image4',
            field=models.ImageField(null=True, upload_to='original_image'),
        ),
        migrations.AddField(
            model_name='controller',
            name='image5',
            field=models.ImageField(null=True, upload_to='original_image'),
        ),
    ]
