# Generated by Django 4.1.3 on 2022-12-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_controller_image2_controller_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='embeddedlinux',
            name='image2',
            field=models.ImageField(null=True, upload_to='original_image'),
        ),
        migrations.AddField(
            model_name='embeddedlinux',
            name='image3',
            field=models.ImageField(null=True, upload_to='original_image'),
        ),
        migrations.AddField(
            model_name='embeddedlinux',
            name='image4',
            field=models.ImageField(null=True, upload_to='original_image'),
        ),
        migrations.AddField(
            model_name='embeddedlinux',
            name='image5',
            field=models.ImageField(null=True, upload_to='original_image'),
        ),
        migrations.AddField(
            model_name='pcbdesigning',
            name='image2',
            field=models.ImageField(null=True, upload_to='original_image'),
        ),
        migrations.AddField(
            model_name='pcbdesigning',
            name='image3',
            field=models.ImageField(null=True, upload_to='original_image'),
        ),
        migrations.AddField(
            model_name='pcbdesigning',
            name='image4',
            field=models.ImageField(null=True, upload_to='original_image'),
        ),
        migrations.AddField(
            model_name='pcbdesigning',
            name='image5',
            field=models.ImageField(null=True, upload_to='original_image'),
        ),
        migrations.AddField(
            model_name='webapp',
            name='image2',
            field=models.ImageField(null=True, upload_to='original_image'),
        ),
        migrations.AddField(
            model_name='webapp',
            name='image3',
            field=models.ImageField(null=True, upload_to='original_image'),
        ),
        migrations.AddField(
            model_name='webapp',
            name='image4',
            field=models.ImageField(null=True, upload_to='original_image'),
        ),
        migrations.AddField(
            model_name='webapp',
            name='image5',
            field=models.ImageField(null=True, upload_to='original_image'),
        ),
    ]
